-- =====================================================================================
-- Migration: Create flashcards schema
-- Purpose: Initial schema for flashcard generation system
-- Created: 2026-01-04
-- =====================================================================================
-- This migration creates the core tables for the flashcard generation application:
-- - flashcards: stores user flashcards (manual and AI-generated)
-- - generations: tracks AI generation sessions and metrics
-- - generation_error_logs: logs errors during generation process
--
-- All tables include RLS policies to ensure users can only access their own data.
-- =====================================================================================

-- =====================================================================================
-- 1. CREATE CUSTOM TYPES
-- =====================================================================================

-- flashcard_source enum: tracks the origin of each flashcard
-- 'manual': created entirely by the user
-- 'ai-full': generated by AI and accepted without edits
-- 'ai-edited': generated by AI but modified by the user before acceptance
create type flashcard_source as enum ('manual', 'ai-full', 'ai-edited');

-- =====================================================================================
-- 2. CREATE TABLES
-- =====================================================================================
-- IMPORTANT: generations table must be created before flashcards table
-- because flashcards.generation_id references generations.id

-- -------------------------------------------------------------------------------------
-- generations table
-- Purpose: Tracks AI generation sessions and their metrics
-- RLS: Users can only access their own generation history
-- -------------------------------------------------------------------------------------
create table generations (
  -- primary identifier
  id uuid primary key default gen_random_uuid(),
  
  -- ownership: links generation to the user who initiated it
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- input tracking (for privacy, we store only the hash, not the actual text)
  -- hash of the input text (e.g., SHA-256) to detect duplicate requests
  input_text_hash varchar(128) not null,
  
  -- length of the input text in characters (must be between 1000-10000)
  input_text_length integer not null check (input_text_length between 1000 and 10000),
  
  -- performance metrics
  -- duration of the generation process in milliseconds
  duration_ms integer not null,
  
  -- generation results
  -- total number of flashcards generated by AI
  generated_count integer not null check (generated_count >= 0),
  
  -- number of flashcards accepted with edits (nullable until user makes decisions)
  accepted_edited_count integer,
  
  -- number of flashcards accepted without edits (nullable until user makes decisions)
  accepted_unedited_count integer,
  
  -- timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- data integrity constraint: accepted counts cannot exceed generated count
  check (
    (accepted_edited_count is null and accepted_unedited_count is null) or
    (coalesce(accepted_edited_count, 0) + coalesce(accepted_unedited_count, 0) <= generated_count)
  )
);

-- -------------------------------------------------------------------------------------
-- flashcards table
-- Purpose: Stores all user flashcards, both manually created and AI-generated
-- RLS: Users can only access their own flashcards
-- -------------------------------------------------------------------------------------
create table flashcards (
  -- primary identifier
  id uuid primary key default gen_random_uuid(),
  
  -- ownership: links flashcard to the user who owns it
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- optional link to the AI generation session that created this flashcard
  -- null for manually created flashcards
  -- set to null if the generation record is deleted
  generation_id uuid references generations(id) on delete set null,
  
  -- flashcard content
  -- front: the question or prompt (1-200 characters after trimming)
  front text not null check (char_length(btrim(front)) between 1 and 200),
  
  -- back: the answer or explanation (1-500 characters after trimming)
  back text not null check (char_length(btrim(back)) between 1 and 500),
  
  -- source: tracks how this flashcard was created
  source flashcard_source not null,
  
  -- timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  
  -- data integrity constraint: ensures source and generation_id are consistent
  -- manual flashcards must have null generation_id
  -- ai-generated flashcards must have a valid generation_id
  check (
    (source = 'manual' and generation_id is null) or
    (source in ('ai-full', 'ai-edited') and generation_id is not null)
  )
);

-- -------------------------------------------------------------------------------------
-- generation_error_logs table
-- Purpose: Logs errors that occur during AI generation process
-- RLS: Users can view their own error logs; system can insert/update
-- -------------------------------------------------------------------------------------
create table generation_error_logs (
  -- primary identifier
  id uuid primary key default gen_random_uuid(),
  
  -- optional link to the generation session where the error occurred
  -- cascade delete: if generation is deleted, remove associated error logs
  generation_id uuid references generations(id) on delete cascade,
  
  -- ownership: links error log to the user who experienced it
  user_id uuid not null references auth.users(id) on delete cascade,
  
  -- error details
  -- standardized error code for categorization and filtering
  error_code varchar(64) not null,
  
  -- detailed error message (max 1000 characters to prevent abuse)
  -- should be sanitized before storage in application layer
  error_message text not null check (char_length(error_message) <= 1000),
  
  -- timestamp
  created_at timestamptz not null default now()
);

-- =====================================================================================
-- 3. CREATE INDEXES
-- =====================================================================================

-- flashcards indexes
-- composite index for efficient user flashcard queries with sorting
create index flashcards_user_id_idx on flashcards(user_id, created_at);

-- index for quickly fetching all flashcards from a specific generation
create index flashcards_generation_id_idx on flashcards(generation_id);

-- generations indexes
-- composite index for user generation history with sorting
create index generations_user_id_idx on generations(user_id, created_at);

-- generation_error_logs indexes
-- composite index for user error log queries with sorting
create index generation_error_logs_user_id_idx on generation_error_logs(user_id, created_at);

-- index for diagnostics of errors in a specific generation session
create index generation_error_logs_generation_id_idx on generation_error_logs(generation_id);

-- =====================================================================================
-- 4. CREATE TRIGGERS FOR AUTOMATIC TIMESTAMP UPDATES
-- =====================================================================================

-- trigger function to automatically update the updated_at column
-- this ensures updated_at is always accurate without manual intervention
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- apply update_updated_at trigger to flashcards table
create trigger update_flashcards_updated_at
  before update on flashcards
  for each row
  execute function update_updated_at_column();

-- apply update_updated_at trigger to generations table
create trigger update_generations_updated_at
  before update on generations
  for each row
  execute function update_updated_at_column();

-- =====================================================================================
-- 5. ENABLE ROW LEVEL SECURITY (RLS)
-- =====================================================================================

-- enable rls on all tables to ensure data isolation between users
alter table flashcards enable row level security;
alter table generations enable row level security;
alter table generation_error_logs enable row level security;

-- =====================================================================================
-- 6. CREATE RLS POLICIES
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- flashcards RLS policies
-- Users can only access flashcards they own
-- -------------------------------------------------------------------------------------

-- policy: authenticated users can select their own flashcards
create policy "flashcards_select_authenticated"
  on flashcards
  for select
  to authenticated
  using (user_id = auth.uid());

-- policy: authenticated users can insert flashcards for themselves
create policy "flashcards_insert_authenticated"
  on flashcards
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- policy: authenticated users can update their own flashcards
create policy "flashcards_update_authenticated"
  on flashcards
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- policy: authenticated users can delete their own flashcards
create policy "flashcards_delete_authenticated"
  on flashcards
  for delete
  to authenticated
  using (user_id = auth.uid());

-- -------------------------------------------------------------------------------------
-- generations RLS policies
-- Users can only access their own generation history
-- -------------------------------------------------------------------------------------

-- policy: authenticated users can select their own generations
create policy "generations_select_authenticated"
  on generations
  for select
  to authenticated
  using (user_id = auth.uid());

-- policy: authenticated users can insert generations for themselves
create policy "generations_insert_authenticated"
  on generations
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- policy: authenticated users can update their own generations
-- (e.g., to update accepted_edited_count and accepted_unedited_count)
create policy "generations_update_authenticated"
  on generations
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- policy: authenticated users can delete their own generations
create policy "generations_delete_authenticated"
  on generations
  for delete
  to authenticated
  using (user_id = auth.uid());

-- -------------------------------------------------------------------------------------
-- generation_error_logs RLS policies
-- Users can view their own error logs
-- System (authenticated users) can insert error logs for themselves
-- No update/delete for regular users (administrative operation only)
-- -------------------------------------------------------------------------------------

-- policy: authenticated users can select their own error logs
create policy "generation_error_logs_select_authenticated"
  on generation_error_logs
  for select
  to authenticated
  using (user_id = auth.uid());

-- policy: authenticated users can insert error logs for themselves
-- this allows the backend api to log errors on behalf of the user
create policy "generation_error_logs_insert_authenticated"
  on generation_error_logs
  for insert
  to authenticated
  with check (user_id = auth.uid());

-- note: no update or delete policies for generation_error_logs
-- these operations should be restricted to database administrators only
-- if needed, separate policies can be created for service role

-- =====================================================================================
-- 7. DISABLE ALL RLS POLICIES
-- =====================================================================================

-- -------------------------------------------------------------------------------------
-- Drop flashcards RLS policies
-- -------------------------------------------------------------------------------------
drop policy if exists "flashcards_select_authenticated" on flashcards;
drop policy if exists "flashcards_insert_authenticated" on flashcards;
drop policy if exists "flashcards_update_authenticated" on flashcards;
drop policy if exists "flashcards_delete_authenticated" on flashcards;

-- -------------------------------------------------------------------------------------
-- Drop generations RLS policies
-- -------------------------------------------------------------------------------------
drop policy if exists "generations_select_authenticated" on generations;
drop policy if exists "generations_insert_authenticated" on generations;
drop policy if exists "generations_update_authenticated" on generations;
drop policy if exists "generations_delete_authenticated" on generations;

-- -------------------------------------------------------------------------------------
-- Drop generation_error_logs RLS policies
-- -------------------------------------------------------------------------------------
drop policy if exists "generation_error_logs_select_authenticated" on generation_error_logs;
drop policy if exists "generation_error_logs_insert_authenticated" on generation_error_logs;

-- -------------------------------------------------------------------------------------
-- Disable RLS on all tables
-- -------------------------------------------------------------------------------------
alter table flashcards disable row level security;
alter table generations disable row level security;
alter table generation_error_logs disable row level security;

-- =====================================================================================
-- END OF MIGRATION
-- =====================================================================================

